### ISSUE TITLE
How to replace OpenAi model with Goggle Gemini Pro 

### ISSUE THREAD

**Issue by Abhay-404** [AbanteAI/rawdog#15]

**Comment by ancs21** [comment]
hi @Abhay-404 

Inspiration this repo I also created another report here (https://github.com/ancs21/dragala) that supports the Goggle Gemini Pro model by default, Google provides `gemini-pro` model for free so you can try it. 

Thanks.

**Comment by tikendraw** [comment]
Use litellm
1. run the local gemini server posing as openai 
```bash
litellm --model gemini/gemini-pro --port 8080 --debug
```

2. Edit the `.rawdog/config.yaml` accordingly
```yaml
llm_api_key: AIxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxx
llm_base_url: http://0.0.0.0:8080
llm_custom_provider: openai
llm_model: gemini-pro
```
