### ISSUE TITLE
Add config to make --dry-run default

### ISSUE THREAD

**Issue by DavidDworetzky** [AbanteAI/rawdog#49]
In environments where I might be recommending this tool to others - I'd feel better having the safer option be the default. Is there a setting for this currently, or would we have to add a flag/config?

**Comment by biobootloader** [comment]
We could add a `default_dry_run` optional flag to the config!

**Comment by granawkins** [comment]
With #59, you can now set dry-run to default by modifying `~/.rawdog.config.yaml`, after you've opened rawdog once and generated it. e.g:

```yaml
llm_api_key: ...
llm_base_url: https://api.openai.com/v1
llm_custom_provider: null
llm_model: gpt-4-turbo
llm_temperature: '1'
dry_run: True
```
